# Generated by Django 6.0.5 on 2026-05-17 09:30

import game.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_backgroundasset_remove_sessionlog_character_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backgroundasset',
            name='image',
            field=models.FileField(upload_to='backgrounds/', validators=[game.models.validate_background_media]),
        ),
        migrations.AlterField(
            model_name='playerpost',
            name='character_token',
            field=models.FileField(blank=True, null=True, upload_to='player_tokens/', validators=[game.models.validate_token_media]),
        ),
    ]
