# Generated by Django 6.0.5 on 2026-05-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_backgroundasset_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerpost',
            name='character_token',
            field=models.FileField(blank=True, null=True, upload_to='tokens/'),
        ),
        migrations.AlterField(
            model_name='playerpost',
            name='status',
            field=models.CharField(default='PENDING', max_length=10),
        ),
    ]
